name: quarto-setup

on: 
  branch: main

jobs:
  quarto_render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
